# Generated by Django 2.2.1 on 2019-05-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3')], default='A', max_length=25)),
                ('min_water', models.IntegerField()),
                ('max_water', models.IntegerField()),
            ],
        ),
    ]
