# Generated by Django 2.2.1 on 2019-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterDat',
            fields=[
                ('plant_num', models.IntegerField(primary_key=True, serialize=False)),
                ('current_level', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(max_length=25),
        ),
    ]
