# Generated by Django 2.2.1 on 2019-06-01 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190601_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdat',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterdat',
            name='current_level',
            field=models.IntegerField(),
        ),
    ]
