# Generated by Django 2.2.1 on 2019-06-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190601_1125'),
        ('catalog', '0004_auto_20190601_1505'),
    ]

    operations = [
    ]
